In [1]:
import pandas as pd # bring in the pandas library to read in data from a csv file
import numpy as np # bring in the numpy library to perform calculations on the data frame
df = pd.read_csv("CrashDataSet.csv") # reads the CSV file from the project folder
df.head() #shows the first 5 rows of the data frame

  Crash ID\tState\tMonth\tYear\tDayweek\tTime\tCrash Type\tBus Involvement\tHeavy Rigid Truck Involvement\tArticulated Truck Involvement\tSpeed Limit\tRoad User\tGender\tAge\tNational Remoteness Areas\tSA4 Name 2021\tNational LGA Name 2021\tNational Road Type\tChristmas Period\tEaster Period\tAge Group\tDay of week\tTime of day
0  20237008\tNT\t10\t2023\tFriday\t\tSingle\tNo\t...
1  20234009\tSA\t10\t2023\tSaturday\t03:00\tSingl...
2  20233087\tQld\t10\t2023\tSaturday\t03:00\tSing...
3  20233149\tQld\t10\t2023\tSunday\t03:00\tSingle...
4  20233190\tQld\t10\t2023\tSunday\t03:00\tMultip...

In [2]:
import pandas as pd # bring in the pandas library to read in data from a csv file
import numpy as np # bring in the numpy library to perform calculations on the data frame
df = pd.read_csv("CrashDataSet.csv",sep='\t') # reads the CSV file from the project folder
df.head() #shows the first 5 rows of the data frame

C:\Users\ASUS F15\AppData\Local\Temp\ipykernel_87832\442990847.py:3: DtypeWarning: Columns (0: Speed Limit, 1: National Remoteness Areas, 2: SA4 Name 2021, 3: National LGA Name 2021, 4: National Road Type) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("CrashDataSet.csv",sep='\t') # reads the CSV file from the project folder

,Crash ID,State,Month,Year,Dayweek,Time,Crash Type,Bus Involvement,Heavy Rigid Truck Involvement,Articulated Truck Involvement,...,Age,National Remoteness Areas,SA4 Name 2021,National LGA Name 2021,National Road Type,Christmas Period,Easter Period,Age Group,Day of week,Time of day
0,20237008,NT,10,2023,Friday,NaN,Single,No,No,No,...,24,NaN,NaN,NaN,NaN,No,No,17_to_25,Weekend,Night
1,20234009,SA,10,2023,Saturday,03:00,Single,No,No,No,...,22,Outer Regional Australia,Barossa - Yorke - Mid North,Yorke Peninsula,Local Road,No,No,17_to_25,Weekend,Night
2,20233087,Qld,10,2023,Saturday,03:00,Single,No,No,No,...,19,Inner Regional Australia,Wide Bay,Gympie,Collector Road,No,No,17_to_25,Weekend,Night
3,20233149,Qld,10,2023,Sunday,03:00,Single,No,No,No,...,37,Inner Regional Australia,Wide Bay,Bundaberg,Local Road,No,No,26_to_39,Weekend,Night
4,20233190,Qld,10,2023,Sunday,03:00,Multiple,No,No,No,...,35,Outer Regional Australia,Mackay - Isaac - Whitsunday,Mackay,Sub-arterial Road,No,No,26_to_39,Weekend,Night

In [3]:

print("Records:", df.shape[0]) # put print cause otherwise it will not show the output in the notebook
print("Features:", df.shape[1])

print(df.dtypes)

Records: 55360
Features: 23
Crash ID                          int64
State                               str
Month                             int64
Year                              int64
Dayweek                             str
Time                                str
Crash Type                          str
Bus Involvement                     str
Heavy Rigid Truck Involvement       str
Articulated Truck Involvement       str
Speed Limit                      object
Road User                           str
Gender                              str
Age                               int64
National Remoteness Areas           str
SA4 Name 2021                       str
National LGA Name 2021              str
National Road Type                  str
Christmas Period                    str
Easter Period                       str
Age Group                           str
Day of week                         str
Time of day                         str
dtype: object